// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7tHg8xdMPy3mzOzVHgTLLkNsbp69yMn8',
    appId: '1:903859385378:web:3b40e1dd9ecbbe8d3d867b',
    messagingSenderId: '903859385378',
    projectId: 'cpit-education',
    authDomain: 'cpit-education.firebaseapp.com',
    storageBucket: 'cpit-education.firebasestorage.app',
    measurementId: 'G-LDJS61994R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCYtk0qhOIoEiYbnOJnQZGkIa_dI8PIcE',
    appId: '1:903859385378:android:ec326e8335b097e43d867b',
    messagingSenderId: '903859385378',
    projectId: 'cpit-education',
    storageBucket: 'cpit-education.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnj7In1XNtGxjPM7I1neEVqRJIz3YRMt4',
    appId: '1:903859385378:ios:d00f7d7f0db035943d867b',
    messagingSenderId: '903859385378',
    projectId: 'cpit-education',
    storageBucket: 'cpit-education.firebasestorage.app',
    iosBundleId: 'com.cpit.app',
  );
}
